apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-jellyfin-infraweaver-media-ro-ed48cccd
  labels:
    infraweaver.io/nas-share: 'true'
    infraweaver.io/provider: truenas
    infraweaver.io/backend: smb
    infraweaver.io/access: ro
    infraweaver.io/share: infraweaver
    infraweaver.io/subfolder: media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  claimRef:
    namespace: jellyfin
    name: nas-infraweaver-media-ro
  mountOptions:
    - ro
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 10.1.0.135/infraweaver#media#nas-jellyfin-infraweaver-media-ro-ed48cccd
    volumeAttributes:
      source: //10.1.0.135/infraweaver
      subDir: media
    readOnly: true
    nodeStageSecretRef:
      name: nas-truenas-ro
      namespace: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-infraweaver-media-ro
  namespace: jellyfin
  labels:
    infraweaver.io/nas-share: 'true'
    infraweaver.io/provider: truenas
    infraweaver.io/backend: smb
    infraweaver.io/access: ro
    infraweaver.io/share: infraweaver
    infraweaver.io/subfolder: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  volumeName: nas-jellyfin-infraweaver-media-ro-ed48cccd
  resources:
    requests:
      storage: 500Gi
