#!/usr/bin/env bash
# site-link.sh — render and inspect layer-2 site links to remote Proxmox nodes.
#
# A "site link" extends an on-prem VLAN over an existing WireGuard tunnel to a
# remote Proxmox node, using VXLAN. Guests on the remote node then attach to a
# plain bridge and hold addresses in the on-prem subnet, which is what Talos
# control planes, MetalLB L2 and Cilium assume.
#
# The rendered config is deliberately just two /etc/network/interfaces.d
# snippets derived from the site YAML. That keeps the same operation available
# three ways without divergence: this script, a console "add remote site" flow
# driving the Proxmox API, or an operator pasting the output by hand.
#
# Usage:
#   scripts/site-link.sh render hub  sites/hypatia.yaml
#   scripts/site-link.sh render edge sites/hypatia.yaml
#   scripts/site-link.sh status      sites/hypatia.yaml
#
# render writes nothing. Apply on the target node with:
#   scripts/site-link.sh render hub sites/x.yaml | ssh root@<hub> \
#     'cat > /etc/network/interfaces.d/site-<name> && ifup vxlan<vni>'
#
# Design notes that matter if you port this to the console:
#   - The hub side attaches the VXLAN device to the existing VLAN-aware bridge
#     at runtime (ip link set ... master) instead of editing that bridge's
#     bridge-ports. Rewriting bridge-ports triggers a reload of the bridge
#     carrying every production VM on that node.
#   - VLAN 1 is removed from the hub port. Linux adds it as the default PVID
#     when a port joins a VLAN-aware bridge, which would otherwise leak the
#     untagged/management VLAN across the site link.
#   - Overlay MTU is tunnel MTU minus 50. Guests MUST use it. A wrong MTU here
#     passes every ping and silently drops large packets.
set -euo pipefail

usage() { sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }
[ $# -ge 2 ] || usage

ACTION="$1"

case "$ACTION" in
  render) SITE="${3:?site yaml required}" ;;
  status) SITE="${2:?site yaml required}" ;;
  *)      usage ;;
esac
[ -f "$SITE" ] || { echo "site-link: no such site file: $SITE" >&2; exit 1; }

# Minimal reader for the flat two-level schema used by sites/*.yaml.
# Avoids a hard dependency on yq for what is a fixed, known shape.
field() {
  python3 - "$SITE" "$1" <<'PY'
import sys
path, want = sys.argv[1], sys.argv[2].split(".")
stack = {}
for raw in open(path):
    line = raw.split("#")[0].rstrip()
    if not line.strip():
        continue
    indent = len(line) - len(line.lstrip())
    key, _, val = line.strip().partition(":")
    stack = {i: k for i, k in stack.items() if i < indent}
    stack[indent] = key.strip()
    val = val.strip().strip('"').strip("'")
    if [stack[i] for i in sorted(stack)] == want and val:
        print(val)
        break
else:
    sys.exit("site-link: missing field %s in %s" % (".".join(want), path))
PY
}

NAME=$(field name)
HUB_HOST=$(field hub.host);             HUB_NODE=$(field hub.node)
HUB_TUNNEL_IP=$(field hub.tunnel_ip);   HUB_BRIDGE=$(field hub.bridge)
EDGE_HOST=$(field edge.host);           EDGE_NODE=$(field edge.node)
EDGE_TUNNEL_IP=$(field edge.tunnel_ip); EDGE_BRIDGE=$(field edge.bridge)
VLAN=$(field l2.vlan); VNI=$(field l2.vni); DSTPORT=$(field l2.dstport)
TUNNEL_MTU=$(field mtu.tunnel); OVERLAY_MTU=$(field mtu.overlay)

# The overlay MTU is load-bearing; refuse to render a link that would blackhole.
EXPECTED=$((TUNNEL_MTU - 50))
if [ "$OVERLAY_MTU" -ne "$EXPECTED" ]; then
  echo "site-link: mtu.overlay=${OVERLAY_MTU} but tunnel ${TUNNEL_MTU} - 50 = ${EXPECTED}" >&2
  exit 1
fi

render_hub() {
  cat <<EOF
# site-link: ${NAME}  (generated by scripts/site-link.sh — hub side)
# extends VLAN ${VLAN} on ${HUB_BRIDGE} to ${EDGE_NODE} over the tunnel
auto vxlan${VNI}
iface vxlan${VNI} inet manual
	pre-up ip link add vxlan${VNI} type vxlan id ${VNI} local ${HUB_TUNNEL_IP} remote ${EDGE_TUNNEL_IP} dstport ${DSTPORT} || true
	up ip link set vxlan${VNI} mtu ${OVERLAY_MTU} up
	up ip link set vxlan${VNI} master ${HUB_BRIDGE}
	up bridge vlan add dev vxlan${VNI} vid ${VLAN} pvid untagged
	up bridge vlan del dev vxlan${VNI} vid 1
	down ip link del vxlan${VNI} || true
EOF
}

render_edge() {
  cat <<EOF
# site-link: ${NAME}  (generated by scripts/site-link.sh — edge side)
# guests attaching to ${EDGE_BRIDGE} land untagged in the hub's VLAN ${VLAN}
auto vxlan${VNI}
iface vxlan${VNI} inet manual
	pre-up ip link add vxlan${VNI} type vxlan id ${VNI} local ${EDGE_TUNNEL_IP} remote ${HUB_TUNNEL_IP} dstport ${DSTPORT} || true
	up ip link set vxlan${VNI} mtu ${OVERLAY_MTU} up
	down ip link del vxlan${VNI} || true

auto ${EDGE_BRIDGE}
iface ${EDGE_BRIDGE} inet manual
	bridge-ports vxlan${VNI}
	bridge-stp off
	bridge-fd 0
	mtu ${OVERLAY_MTU}
EOF
}

# Transport for `status`. Override when the hub and edge need different
# credentials, e.g. SSH_OPTS="-i ~/.ssh/env_deployer". A console driving this
# supplies its own transport and only needs the render output.
SSH_BIN="${SSH_BIN:-ssh}"
SSH_OPTS="${SSH_OPTS:--o BatchMode=yes}"

probe() {  # probe <host> <remote-command>
  # shellcheck disable=SC2086
  $SSH_BIN $SSH_OPTS -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
    "root@$1" "$2" 2>/dev/null || echo "  unreachable"
}

status() {
  echo "site-link: ${NAME}  (VLAN ${VLAN} -> VNI ${VNI}, overlay MTU ${OVERLAY_MTU})"
  echo "--- hub ${HUB_NODE} (${HUB_HOST}) ---"
  probe "${HUB_HOST}" \
    "ip -br link show vxlan${VNI} 2>/dev/null || echo '  vxlan${VNI} ABSENT';
     bridge vlan show dev vxlan${VNI} 2>/dev/null | tail -n +2"
  echo "--- edge ${EDGE_NODE} (${EDGE_HOST}) ---"
  probe "${EDGE_HOST}" \
    "ip -br link show vxlan${VNI} 2>/dev/null || echo '  vxlan${VNI} ABSENT';
     ip -br link show ${EDGE_BRIDGE} 2>/dev/null || echo '  ${EDGE_BRIDGE} ABSENT'"
}

case "$ACTION" in
  render)
    case "$2" in
      hub)  render_hub ;;
      edge) render_edge ;;
      *)    echo "site-link: render target must be 'hub' or 'edge'" >&2; exit 1 ;;
    esac
    ;;
  status) status ;;
esac
